### ISSUE TITLE
docs: Enhance Unleash documentation (parent issue)

### ISSUE THREAD

**Issue by gazconroy** [Unleash/unleash#673]
### Sub-issues and potential sub-issues
**Housekeeping (internal - Slack channel?)**
- [x] Complete a documentation project plan
- [x] Identify overlap with other projects - such as v4
- [x] Identify content or groups of content that require a sub-issue (any new page plus others that may require significant work) - based on the following lists

**The basics**
- [x] Unleash overview (new overview page - possibly combine with quick start guide)
- [x] Quick start guide (new tutorial/overview page - possibly combine with Unleash overview)
- [ ] Glossary - based on an extended version of unleash-hosted.com/glossary

**Feature toggles**
- [ ] How to use the server dashboard (tutorial) - based on unleash-hosted.com/docs/create-feature-toggle
- [x] Feature toggle types (reference guide) - from unleash.github.io/docs/feature_toggle_types
- [x] Variants (reference guide) - from unleash.github.io/docs/toggle_variants
- [ ] Control feature rollout (reference guide) - from unleash.github.io/docs/activation_strategy
- [ ] How to roll out a feature (tutorial/video) - from youtu.be/Lp0-q1bJUWE
- [ ] Usage monitoring (reference guide) - from unleash.github.io/docs/api/internal
- [ ] Import and export (reference guide) - from unleash.github.io/docs/import_export
- [ ] How to (and why you should) use the Unleash feature toggle system to achieve objective A, B, C... (new blog articles and/or tutorials)

**SDK**
- [x] Overview (plus tutorials) - based on unleash-hosted.com/docs/use-feature-toggle

**API**
- [x] API overview - base on github.com/thegooddocsproject/templates/blob/master/api-overview/about-overview.md
- [ ] API quick reference (Open API specification) - see #667 - possibly incoporate the API overview into it
- [ ] Status and error codes (new reference guide)
- [ ] Rate limiting - if it's a 'thing' and if not, why not (new reference guide)

**Admin/server reference**
- [ ] Server setup  (reference/tutorial) - extend from unleash.github.io/docs/getting_started
- [ ] Securing Unleash  (reference guide/tutorial) - extend unleash.github.io/docs/securing_unleash
- [ ] Database setup  (reference guide) - base on unleash.github.io/docs/developer_guide
- [ ] Database configuration (new reference guide - part of the old 'Gettiing started' page)
- [ ] Database schema (reference guide) - from unleash.github.io/docs/database_schema
- [ ] Migrating between versions of Unleash (reference guide) - from unleash.github.io/docs/migration_guide

**Client reference**
- [ ] Client specification (reference guide) - from unleash.github.io/docs/client_specification
- [ ] Unleash context (reference guide) - from unleash.github.io/docs/unleash_context
- [ ] Multi-platform tutorials (how to use platform A to do tasks X, Y and Z)

**Integrations**
- [x] Slack (tutorial) - from unleash.github.io/docs/guides/feature_updates_to_slack 
- [x] Others (new tutorial pages as required)

**Comment by thomasheartman** [comment]
Just a little update comment on this 🙋🏼 

We're working heavily on updating the documentation at the moment, including (probably) restructuring it to make it easier to find things. Most of the unchecked points mentioned in this issue still apply (and are really good, important points!), however, so I'll leave it open for now and come back and update it when we make changes that are related.

**Comment by ivarconr** [comment]
I will close this, as it is fair to say we have adopted a lot of these and done major restructures of the docs last few weeks @thomasheartman
