### ISSUE TITLE
We have a Public Unleash Roadmap

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#879]
Hi all, we recently opened our internal [Unleash Roadmap](https://github.com/orgs/Unleash/projects/5) and made it public 🚀 

We need to make it available on **multiple** places:

- [ ] In our README.md
- [x] In the footer of [docs.getunleash.io](https://docs.getunleash.io)
- [x] In the footer of [www.getunleash.io](https://www.getunleash.io)

Other places?

**And please, as always, please provide any feedback on what you think is important for us to focus on!**
